### ISSUE TITLE
Develop API for workout application

### ISSUE THREAD

**Issue by zakh-d** [zakh-d/workout-app-backend#1]
- [ ] CRUD operation for Workout model
- [ ] CRUD operation for Exercise model
- [ ] Permissions
- [ ] Authentication via JWTs
